// styles.js

import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#B0D9B1",
  },
  header: {
    backgroundColor: "#B0D9B1",
    textAlign: "center",
    fontVariant: "bold",
    color: "#B0D9B1",
    paddingBottom: 20,
  },
  title: {
    backgroundColor: "#B0D9B1",
    textAlign: "center",
    fontSize: 40,
    fontWeight: "bold",
    color: "#B0D9B1",
    paddingTop: 30,
  },
  text: {
    color: "#B0D9B1",
    paddingRight: 20,
    paddingLeft: 20,
    marginBottom: 20,
    textAlign: "center",
  },
  subsection: {
    flexDirection: "column",
    justifyContent: "center",
    alignContent: "space-around",
  },
  subheading: {
    color: "#B0D9B1",
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "center",
    paddingTop: 20,
    paddingBottom: 20,
    marginTop: -10,
  },
  text: {
    color: "#B0D9B1",
    paddingRight: 20,
    paddingLeft: 20,
    marginBottom: 20,
    textAlign: "center",
    fontSize: 18,
    backgroundColor: "#00000080",
    borderRadius: 10,
    padding: 10,
    marginHorizontal: 10,
  },
  subsection: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignContent: "space-around",
    flex: 1,
  },
  subheading: {
    color: "#B0D9B1",
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "center",
    paddingTop: 20,
    marginTop: -10,
    backgroundColor: "#00000080",
    borderRadius: 10,
    padding: 10,
  },
  footer: {
    justifyContent: "flex-end",
    paddingVertical: 20,
  },
  buttonContainer: {
    flexDirection: "row",
    width: "100%",
  },
  button: {
    backgroundColor: "#B0D9B1",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
    marginHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
  },
  marginTopText: {
    color: "#B0D9B1",
    paddingRight: 20,
    paddingLeft: 20,
    marginBottom: 20,
    textAlign: "center",
    marginTop: 20,
    fontSize: 18,
    backgroundColor: "#00000080",
    borderRadius: 10,
    padding: 10,
    marginHorizontal: 10,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  checkboxLabel: {
    marginLeft: 10,
    color: "#B0D9B1",
    fontSize: 16,
  },
  backgroundVideo: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});
