const BooksJson = [
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/09/law-of-success.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/09/hypmanic.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/09/how-to-win-250x375.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/09/barbarians-1.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/09/power-vs-force.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/great_business_teams.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/crucial-conversations.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/mastery.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-e-myth-revisited.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/33-strategies-of-war.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/tribal-leadership.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/48-laws-of-power.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/art-of-seduction.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/a-first-rate-madness.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/how-to-master-the-art-of-selling.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/made-in-a-america.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-lean-startup.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-road-to-freedom.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/david-and-goliath.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/lincoln-on-leadership.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/meditations.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/outwitting-the-devil.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/eleven-rings-phil-jackson.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/psycho-cybernetics.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-ultimate-gift.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-essential-drucker.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/fish-a-proven-way-to-boost-morale-and-improve-results.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/body-for-life.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/atlas-shrugged.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-art-of-war.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/pushing-up-people-3.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-5-love-languages.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-greatest-salesman-in-the-world.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/15-invaluable-laws-of-growth.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-true-believer.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-nicomachean-ethics.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/a-few-lessons-for-investors-and-managers.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/acting-in-film.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/blue-ocean-strategy.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-screwtape-letters.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/start-with-why.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/21-irrefutable-laws-of-leadership.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/101-questions-to-ask-before-you-get-engaged.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-power-of-ethical-management.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/love-respect.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/think-and-grow-rich.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-prince.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-wealth-of-nations.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/common-sense.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-age-of-reason.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-analects-of-confucious.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/democracy-in-america.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-abc-of-building-a-business-team.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/7-strategies-for-wealth-and-happiness.jpeg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-wit-and-wisdom-of-abraham-lincoln.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/cyrus-the-great-the-art-of-leadership-and-war.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-law.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/capitalism-and-freedom.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/emotional-intelligence.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-alchemist.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/delivering-happiness.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/built-to-last.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/secrets-of-the-millionaire-mind.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/id-like-the-world-to-buy-a-coke.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/spy-the-lie.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/how-capitalism-will-save-us.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/rich-dad-poor-dad.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/beyond-positive-thinking.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/they-call-me-coach.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/17-indisputable-laws-of-teamwork.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-five-dysfunctions-of-a-team.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/winners-never-cheat.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/mans-search-for-meaning.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-magic-of-thinking-big.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/everyone-communicates-few-connect.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/accidental-millionaire.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/a-gentleman-gets-dressed-up.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/how-to-be-a-lady.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/how-to-become-a-rainmaker.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/outliers-the-story-of-success.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-leadership-secrets-of-billy-graham.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/poor_charlies_almanack_2.png",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-book-thief.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/up-the-organization.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-obstacle-is-the-way.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/winning-jack-welch.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/how-to-stop.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-game-neil-strauss.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/power-of-habit.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-greatest-minds-ideas.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-four-agreements.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-samson-syndrome.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/crush-it.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/innovation-and-entrepreneurship.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/how-not-to-be-wrong.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/working-together.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/wit-and-wisdom-of-the-american-presidents.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/zen-golf.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/game-of-numbers.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-road-to-serfdom.jpg",
];

const BooksCaption = [
  "#1 THE LAW OF SUCCESS",
  "#2 THE HYPOMANIC EDGE",
  "#3 HOW TO WIN FRIENDS & INFLUENCE PEOPLE",
  "#4 BARBARIANS TO BUREAUCRATS",
  "#5 POWER VS. FORCE",
  "#6 GREAT BUSINESS TEAMS",
  "#7 CRUCIAL CONVERSATIONS",
  "#8 MASTERY",
  "#9 E-MYTH",
  "#10 33 STRATEGIES OF WAR",
  "#11 TRIBAL LEADERSHIP",
  "#12 THE 48 LAWS OF POWER",
  "#13 THE ART OF SEDUCTION",
  "#14 FIRST RATE MADNESS",
  "#15 HOW TO MASTER THE ART OF SELLING",
  "#16 SAM WALTON MADE IN AMERICA",
  "#17 THE LEAN STARTUP",
  "#18 THE ROAD TO FREEDOM",
  "#19 DAVID AND GOLIATH",
  "#20  LINCOLN ON LEADERSHIP",
  "#21 MEDITATIONS BY MARCUS AURELIUS",
  "#22 OUTWITTING THE DEVIL",
  "#23 11 RINGS BY PHIL JACKSON",
  "#24 PSYCHO- CYBERNETICS",
  "#25 THE ULTIMATE GIFT",
  "#26 ESSENTIAL DRUCKER",
  "#27 FISH BY STEPHEN C. LUNDIN AND HARRY PAUL",
  "#28 BODY FOR LIFE",
  "#29 ATLAS SHRUGGED",
  "#30 ART OF WAR BY SUN TZU",
  "#31 PUSHING UP PEOPLE",
  "#32 THE FIVE LOVE LANGUAGES",
  "#33 THE GREATEST SALESMAN IN THE WORLD",
  "#34 15 INVALUABLE LAWS OF GROWTH",
  "#35 THE TRUE BELIEVER",
  "#36 THE NICHOMACHEAN ETHICS",
  "#37 A FEW LESSONS FOR INVESTORS AND MANAGERS",
  "#38 ACTING IN FILM BY MICHAEL CAINE",
  "#39 BLUE OCEAN STRATEGY",
  "#40 SCREWTAPE LETTERS",
  "#41 START WITH WHY",
  "#42 IRREFUTABLE LAWS OF LEADERSHIP – LEADERSHIP 101",
  "#43 101 QUESTIONS TO ASK BEFORE YOU GET ENGAGED",
  "#44 THE POWER OF ETHICAL MANAGEMENT",
  "#45 LOVE & RESPECT",
  "#46 THINK AND GROW RICH",
  "#47 THE PRINCE",
  "#48 THE WEALTH OF NATIONS",
  "#49 COMMON SENSE",
  "#50 THE AGE OF REASON",
  "#51 THE ANALECTS CONFUCIOUS",
  "#52 DEMOCRACY IN AMERICA",
  "#53 ABC’S OF BUILDING A BUSINESS TEAM THAT WINS",
  "#54 7 STRATEGIES FOR WEALTH & HAPPINESS",
  "#55 THE WIT AND WISDOM OF ABRAHAM LINCOLN",
  "#56 CYRUS THE GREAT: THE ARTS OF LEADERSHIP AND WAR",
  "#57 THE LAW",
  "#58 CAPITALISM & FREEDOM",
  "#59 EMOTIONAL INTELLIGENCE 2.0",
  "#60 THE ALCHEMIST",
  "#61 DELIVERING HAPPINESS",
  "#62 BUILT TO LAST",
  "#63 SECRETS OF THE MILLIONAIRE MIND",
  "#64 I’D LIKE THE WORLD TO BUY A COKE: THE LIFE AND LEADERSHIP OF ROBERTO GOIZUETA",
  "#65 SPY THE LIE",
  "#66 HOW CAPITALISM WILL SAVE US",
  "#67 RICH DAD POOR DAD",
  "#68 BEYOND POSITIVE THINKING",
  "#69 THEY CALL ME COACH",
  "#70 17 INDISPUTABLE LAWS OF TEAMWORK",
  "#71 THE 5 DYSFUNCTIONS OF A TEAM",
  "#72 WINNERS NEVER CHEAT",
  "#73 MAN’S SEARCH FOR MEANING",
  "#74 MAGIC OF THINKING BIG",
  "#75 EVERYONE COMMUNICATES, FEW CONNECT",
  "#76 ACCIDENTAL MILLIONAIRE",
  "#77 A GENTLEMEN GETS DRESSED UP",
  "#78 HOW TO BE A LADY",
  "#79 HOW TO BECOME A RAINMAKER",
  "#80 OUTLIERS: THE STORY OF SUCCESS",
  "#81 THE LEADERSHIP SECRETS OF BILLY GRAHAM",
  "#82 POOR CHARLIE’S ALMANACK: THE WIT AND WISDOM OF CHARLES T. MUNGER",
  "#83 THE BOOK THIEF",
  "#84 UP THE ORGANIZATION",
  "#85 THE OBSTACLE IS THE LAW",
  "#86 WINNING",
  "#87  HOW TO STOP WORRYING AND START LIVING",
  "#88 THE GAME",
  "#89 THE POWER OF HABIT",
  "#90 THE GREATEST IDEAS AND MINDS OF ALL TIME",
  "#91 THE FOUR AGREEMENTS",
  "#92 SAMSON SYNDROME",
  "#93 CRUSH IT",
  "#94 INNOVATION & ENTREPRENEURSHIP",
  "#95 HOW NOT TO BE WRONG",
  "#96 WORKING TOGETHER",
  "#97 WIT AND WISDOM OF THE AMERICAN PRESIDENT",
  "#98 ZEN GOLF",
  "#99 GAME OF NUMBERS",
  "#100 THE ROAD TO SERFDOM",
];

export { BooksJson, BooksCaption };
