const quotes = [
  "David Goggins: 'The only way to grow stronger is to embrace the discomfort of hard work.'",
  "Patrick Bet-David: 'The only limits that exist are the ones you place on yourself.'",
  "David Goggins: 'You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.'",
  "Patrick Bet-David: 'The pain of today is the victory of tomorrow.'",
  "David Goggins: 'Life is one big tug-of-war between mediocrity and trying to find your best self.'",
  "Patrick Bet-David: 'Your excuses are nothing more than the lies your fears have sold you.'",
  "David Goggins: 'The mind is the most powerful thing in the world. The mind has capabilities that are so unknown, and being able to tap into that is on the other side of suffering.'",
  "Patrick Bet-David: 'You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.'",
  "David Goggins: 'The worst thing that can happen to a man is to become civilized.'",
  "Patrick Bet-David: 'When you have a sense of calling, whether it’s to be a musician, soloist, artist, a painter, a construction worker, or a comedienne, there is something deep and enriching when you realize it isn’t just a casual choice, it’s a divine calling.'",
  "David Goggins: 'It's so easy to be great nowadays, because everyone else is weak.'",
  "Patrick Bet-David: 'The difference between the successful and the unsuccessful is simply this: one woman takes the risk while the other sits on her ass.'",
  "David Goggins: 'It's not necessarily the amount of time you spend at practice that counts; it's what you put into the practice.'",
  "Patrick Bet-David: 'You don't get to the top by doing what everybody else does.'",
  "David Goggins: 'Don't let the choices of your past dictate who you are today.'",
  "Patrick Bet-David: 'Success is not for the lazy, the timid, or the short-term thinkers. Success is for those who seek the truth and find their own answers, not the ones that are handed to them.'",
  "David Goggins: 'Suffering is a test. That test is what gives you an edge.'",
  "Patrick Bet-David: 'The road to success is the road less traveled by.'",
  "David Goggins: 'The most important conversation is the one you have with yourself.'",
  "Patrick Bet-David: 'The hardest thing to do is to be true to yourself, especially when everybody is watching.'",
  "David Goggins: 'The only way you gain mental toughness is to do things you're not happy doing.'",
  "Patrick Bet-David: 'There is no such thing as bad publicity as long as they get your name right.'",
  "David Goggins: 'A lot of us don't know about another world that exists for us because it's on the other side of suffering.'",
  "Patrick Bet-David: 'Winners don't focus on the pain, they focus on the results.'",
  "David Goggins: 'The things that haunt you are the things you didn't do, not the things you did.'",
  "Patrick Bet-David: 'The price of discipline is always less than the pain of regret.'",
  "David Goggins: 'The most important thing you can do in life is to continuously overcome things you don't want to overcome.'",
  "Patrick Bet-David: 'The key to winning is poise under stress.'",
  "David Goggins: 'The most dangerous person is the one who listens, thinks, and observes.'",
  "Patrick Bet-David: 'The moment you give up is the moment you let someone else win.'",
  "David Goggins: 'When you fall down, focus on the solution, not the problem.'",
  "Patrick Bet-David: 'The only limitations you have are the ones you place on yourself.'",
  "David Goggins: 'Don’t be the person that looks at life as it is; be the person that looks at life as it can be.'",
  "Patrick Bet-David: 'Your best teacher is your last mistake.'",
  "David Goggins: 'If you're looking for a way out, you're going to find a way out.'",
  "Patrick Bet-David: 'When you’re in business for yourself, you’re playing to win, not to avoid losing.'",
  "David Goggins: 'Embrace the suck.'",
  "Patrick Bet-David: 'When you’re working on something you’re passionate about, you don’t need to be pushed. The vision pulls you.'",
  "David Goggins: 'The only person who was going to turn my life around was me.'",
  "Patrick Bet-David: 'If you don’t have a vision for the future, then your future is threatened to be a repeat of the past.'",
  "David Goggins: 'You have to create your own path.'",
  "Patrick Bet-David: 'The best revenge is massive success.'",
  "David Goggins: 'You are stopping your growth by telling yourself you’re too tired.'",
  "Patrick Bet-David: 'The person you become is more important than the money you make.'",
  "David Goggins: 'Procrastination is one of the most common and deadliest of diseases and its toll on success and happiness is heavy.'",
  "Patrick Bet-David: 'Doubt kills more dreams than failure ever will.'",
  "Patrick Bet-David: 'The bigger the goal, the bigger the challenges; the bigger the challenges, the stronger you have to become to overcome them.'",
  "David Goggins: 'It's not about how bad you want it. It's about how hard you're willing to work for it.'",
  "Patrick Bet-David: 'Do not overthink. Overthinking will stop you from making things happen.'",
  "David Goggins: 'The only way to know how strong you are is to keep testing your limits.'",
  "Patrick Bet-David: 'Success always involves risk.'",
  "David Goggins: 'Don't wait for things to be perfect before you decide to enjoy your life.'",
  "Patrick Bet-David: 'The only way to escape the mediocre is to be different. You have to stand out.'",
  "David Goggins: 'I'm going to callous my mind and body.'",
  "Patrick Bet-David: 'If you don't challenge yourself, you will never realize what you can become.'",
];

export default quotes;
