const MoviesJson = [
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/godfather-trilogy.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/rocky-trilogy.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/American-Gangster.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/count-of-montecristo.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/casino.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Cocktail.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Pursuit-of-Happiness-Excuses-and-entrepreneurship-don’t-go-together..jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/goodfellas-movie.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/house-of-cards-first-season.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-social-network-movie-poster.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/steve-jobs.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/It’s-a-wonderful-life-remember-what-you’re-fighting-for..jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-aviator.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/glengarry-glen-ross.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/a-few-good-men.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Wall-street.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Fist.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/boiler-room.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/flash-of-genius.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/8-mile.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/scarfaceposter.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Scent_of_a_Woman.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/good-will-hunting.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/oceans-11.jpeg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/seabiscuit.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Moneyball_Poster.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/wolf-of-wall-street.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Book_of_eli_poster.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Jerry-Maguire.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/shawshank-redemption.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/prefontaine.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/warrior.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/any-given-sunday-dvd.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/two-for-the-money.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/rudy-11.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/tiger-dvd.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/fighter.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/patriot.jpeg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/gladiator.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/limitless.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/i-am-legend-movie.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Dead_poets_society.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/The-champ.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/muhammad-ali.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/arnold.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Carlitos_Way.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/lawless-movie.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/fight-club.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/remember-the-titans.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/just-the-ticket.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/cinderella-man.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/catch-me-if-you-can.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/blow.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/disconnect.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Mighty_ducks.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/MV5BMTQyNTQ4MTAzNl5BMl5BanBnXkFtZTcwMjk2Njk3OA@@._V1_SX640_SY720_.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/iron-lady.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/forrestgump.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/ray.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-hustler.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-great-debaters-movie-poster-2007-1020447313.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/jordan.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/sting.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/gotti.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/click.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-family-man.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/lean-on-me.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/bugsy.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/a-good-year.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/marshall.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/tyson.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Margin_Call.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/a_bronx_tale.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Indecent_proposal.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/large_uRIYDisJdKKZ60i5mR6vq9XchJU.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/DVD-cover.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/61.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/field-of-dreams.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/braveheartfeatured.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/511FTFSVS4L.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/money-never-sleeps.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/hoffa.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/saving-private-ryan.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/Usual_suspects_ver1.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/RoundersPoster.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/DjangoUnchainedInside2_0.png",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/the-town.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/other-peoples-money.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/rogue-trader.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/trading-places.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/colors.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/arbitrage.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/gangster-squad-dvd-cover-76.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/miracle.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/rush.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/white-men-cant-jump.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/url.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/argo1.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/when-we-were-kings1.jpg",
  "https://www.patrickbetdavid.com/wp-content/uploads/2016/10/40-Year-OldVirginMoviePoster.jpg",
];

const MoviesCaption = [
  "#1 THE GODFATHER TRILOGY LEARN THE POWER PLAY & POLITICAL GAMES IN BUSINESS",
  "#2 ROCKY SERIES THE UNDERDOG STORY OF ALL ENTREPRENEURS & ROCKY",
  "#3 AMERICAN GANGSTER THE IMPORTANCE OF PAYING ATTENTION TO DETAILS",
  "#4 THE COUNT OF MONTE CRISTO THE POWER OF RECREATING YOURSELF THROUGH PERSONAL DEVELOPMENT",
  "#5 CASINO YOUR FRIENDS COULD END UP BEING YOUR ENEMIES",
  "#6 PEOPLE WILL CRITICIZE YOUR DREAMS",
  "#7 PURSUIT OF HAPPINESS EXCUSES AND ENTREPRENEURSHIP DON’T GO TOGETHER",
  "#8 GOODFELLAS KNOWING WHICH BRIDGE TO BURN & WHICH TO JUST WALK ACROSS",
  "#9 HOUSE OF CARDS HOW TO DEAL WITH THE FRANK UNDERWOOD’S OF THE WORLD",
  "#10 THE SOCIAL NETWORK NOT EVERY BUSINESS WILL END UP BEING AS BIG AS FACEBOOK AND THAT’S OK",
  "#11 STEVE JOBS THE MADNESS BEHIND BEING A CEO",
  "#12 IT’S A WONDERFUL LIFE REMEMBER WHAT YOU’RE FIGHTING FOR",
  "#13 THE AVIATOR ALL GREAT ENTREPRENEURS HAVE A TOUCH OF MADNESS",
  "#14 GLEN GARY GLEN ROSS SELLING IS A MUST AS AN ENTREPRENEUR",
  "#15 A FEW GOOD MEN YOU NEED A GOOD TEAM WHO’S BROUGH INTO YOU AND YOUR CAUSE",
  "#16 WALL STREET YOU CAN’T BUILD AN EMPIRE FROM PRISON",
  "#17 FIST HOW TO CREATE YOUR OWN MOVEMENT",
  "#18 BOILER ROOM MANY ENTREPRENEURS ARE ONE DUMB DECISION AWAY FROM DOING TIME",
  "#19 FLASH OF GENIUS DON’T LET THE BIG BOYS BULLY YOU",
  "#20  8 MILE SEIZE THE “ONE SHOT, ONE OPPORTUNITY.”",
  "#21 SCARFACE AVOID COCAINE AT ALL COST",
  "#22 SCENT OF A WOMAN NOT REALLY FOR ENTREPRENEURS. I JUST LOVE THIS MOVIE",
  "#23 GOOD WILL HUNTING MOST ENTREPRENEURS ARE USUALLY THEIR OWN WORST ENEMY",
  "#24 OCEAN’S 11 HIRE PEOPLE WHO ARE STRONG IN AREAS YOU ARE WEAK",
  "#25 SEABISCUIT THE BIG AND POWERFUL STALLION CAN BE BEAT DON’T LET BIGGER CORPORATIONS INTIMIDATE YOU",
  "#26 MONEYBALL MATH IS YOUR BEST FRIEND. FIND A PHILOSOPHY THAT WORKS AND STICK TO IT",
  "#27 THE WOLF OF WALL STREET ONLY HAVE SEX WITH THE EMPLOYEE YOU MARRY",
  "#28 THE BOOK OF ELI WHEN YOU’RE CLEAR ABOUT YOUR CAUSE, ALL STARS LINE UP IN YOUR FAVOR.",
  "#29 JERRY MAGUIRE WRITING A MEMO WHEN YOU’RE DRUNK MAY NOT BE THE BEST IDEA.",
  "#30 THE SHAWSHANK REDEMPTION THE POWER OF KEEPING YOUR WORD",
  "#31 PREFONTAINE THE SPIRIT OF COMPETITION IS A MUST AS AN ENTREPRENEUR",
  "#32 WARRIOR IT TAKES LONGER TO WIN THE SUPPORT OF YOUR BIGGEST CRITIC; YOUR FAMILY",
  "#33 ANY GIVEN SUNDAY THE HARDEST THING TO DO AS A LEADER IS TO UNITE YOUR TEAM",
  "#34 TWO FOR THE MONEY DON’T GAMBLE WITH INVESTORS’ MONEY",
  "#35 RUDY YOU DON’T HAVE TO BE A HARVARD GRADUATE OR A DROP OUT TO MAKE IT IN BUSINESS",
  "#36 TIGER WOODS INTERVIEWS OF HIM WHEN HE WAS YOUNGER",
  "#37 THE FIGHTER NEVER FORGET WHERE YOU COME FROM",
  "#38 THE PATRIOT YOU MAY GET KILLED IN BATTLE IF YOU’RE NOT MENTALLY READY",
  "#39 GLADIATOR KEEP YOUR WHY’S IN FRONT OF YOU AT ALL TIME",
  "#40 LIMITLESS I KNOW WHERE TO FIND NZT IF YOU WANT SOME",
  "#41 I AM LEGEND THE ROAD WILL BE LONELY AT TIMES WITH COMPETITORS HOPING TO KILL YOU",
  "#42 DEAD POETS SOCIETY ENJOY THE PROCESS INSTEAD OF BEING IN A HURRY TO REACH THE DESTINATION",
  "#43 THE CHAMP REMEMBER WHAT YOU’RE FIGHTING FOR",
  "#44 ALI YOU CAN ACTUALLY CHANGE THE WORLD WITH YOUR COMPANY",
  "#45 PUMPING IRON WHO ARNOLD WAS BEFORE HE BECAME ARNOLD",
  "#46 CARLITO’S WAY ONCE YOU DEVELOP BAD HABITS, IT’S VERY EASY TO GO BACK TO IT",
  "#47 LAWLESS STICK TOGETHER",
  "#48 FIGHT CLUB NO SPECIFIC REASON. IT’S JUST A COOL MOVIE",
  "#49 REMEMBER THE TITANS HOW TO BRING PEOPLE TOGETHER WHO HAVE OPPOSING BELIEFS",
  "#50 JUST THE TICKET HOW TO HUSTLE ALL DAY LONG",
  "#51 CINDERELLA MAN IT’S GOING TO BE VERY UGLY BEFORE IT GETS GOOD",
  "#52 CATCH ME IF YOU CAN BEING TOO CREATIVE COULD GET YOU CAUGHT UP WORKING FOR THE GOVERNMENT",
  "#53 BLOW AGAIN, AVOID COCAINE AT ALL COST.",
  "#54 DISCONNECT STAY CONNECTED TO YOUR KIDS WHILE BUILDING YOUR BUSINESS.",
  "#55 MIGHTY DUCKS ANOTHER GREAT UNDERDOG STORY",
  "#56 GHANDI KEEP SELLING YOUR VISION AND MISSION",
  "#57 IRON LADY GENDER HAS NOTHING TO DO WITH LEADING AN EMPIRE",
  "#58 FORREST GUMP RUN FOREST RUN. AS AN ENTREPRENEUR YOU’LL NEED TO LEARN HOW TO RUN BEFORE YOU CAN WALK.",
  "#59 RAY THERE WILL BE PEOPLE WHO WANT TO TAKE ADVANTAGE OF YOUR NAIVENESS",
  "#60 THE HUSTLER THERE’S ALWAYS SOMEONE BETTER THAN YOU AT WHAT YOU DO",
  "#61 THE GREAT DEBATERS DON’T WASTE YOUR TIME DEBATING WITH THE WRONG PEOPLE",
  "#62 ULTIMATE JORDAN WATCH GREATNESS AT ITS BEST",
  "#63 STING DOCUMENTARY HOW STING AND HIS TEAM HANDLED 9/11 DURING A VISIT TO HIS PLACE IN ITALY",
  "#64 GOTTI THE POWER GAME",
  "#65 CLICK WE’RE ALL MORTAL AND THIS THING WILL GO VERY QUICKLY. TAKE TIME FOR THOSE YOU LOVE THE MOST.",
  "#66 FAMIY MAN HOW TO MANAGE YOUR TIME IN ORDER TO HAVE A GREAT BUSINESS AND FAMILY LIFE",
  "#67 LEAN ON ME EVERYTHING RISES AND FALLS ON LEADERS ",
  "#68 BUGSY IF YOU’RE GOING TO A CASINO, GO BECAUSE YOU OWN ONE, NOT JUST TO GAMBLE YOUR MONEY AWAY.",
  "#69 A GOOD YEAR REMEMBER YOUR ROOTS",
  "#70 WE ARE MARSHALL CRISIS MANAGEMENT",
  "#71 TYSON SURROUND YOURSELF WITH STRONG ADVISORS",
  "#72 MARGIN CALL THE ONLY SHORT CUT IS TO DO IT RIGHT THE FIRST TIME",
  "#73 A BRONX TALE REMEMBER WHO THE IMPORTANT PEOPLE IN YOUR LIFE ARE",
  "#74 INDECENT PROPOSAL IF YOU’RE MARRIED TO DEMI MOORE, MAKE SURE SHE DOESN’T RUN INTO ROBERT REDFORD.",
  "#75 THE COLOR OF MONEY THERE’S ALWAYS A WOLF COMING UP WHO WANTS TO TAKE OVER YOUR POSITION.",
  "#76 HOOSIERS YOU ALWAYS NEED TO RALLY YOUR TEAM",
  "#77 61 NOT ALL CEO’S HAVE THE SAME PERSONALITY.",
  "#78 FIELD OF DREAMS IF YOU BUILD IT, THEY WILL COME.",
  "#79 BRAVEHEART BY FAR THE BEST FREEDOM SPEECH IN ANY MOVIE",
  "#80 MAN ON FIRE WHEN YOU’RE CLEAR ON YOUR WHY THE HOW DOESN’T MATTER",
  "#81 MONEY NEVER SLEEPS ONCE YOU LEARN THE GAME OF MONEY, IT NEVER GOES AWAY.",
  "#82 HOFFA YOU LEARN A LOT ABOUT SOMEONE WHEN YOU GIVE THEM POWER",
  "#83 SAVING PRIVATE RYAN NO ENTREPRENEUR’S JOB IS AS RISKY AS WHAT SOLDIERS DO IN BATTLE FOR US.",
  "#84 USUAL SUSPECTS BE SLOW TO TRUST SOMEONE NEW WHO’S WAY TOO IMPRESSIVE",
  "#85 ROUNDERS THERE’S NOT MUCH DIFFERENCE BETWEEN PLAYING POWER AND PLAYING ENTREPRENEUR",
  "#86 DJANGO UNCHAINED HOW TO MASTER SALES",
  "#87  THE TOWN IF YOUR BUSINESS ISN’T SUCCESSFUL, DON’T ROB A BANK.",
  "#88 OTHER PEOPLE’S MONEY BE SLOW TO SELL YOUR BUSINESS OR PARTNER UP WITH SOMEONE",
  "#89 ROGUE TRADER HIRE CHARACTER AND INTEGRITY NO MATTER HOW TALENTED SOMEONE IS",
  "#90 TRADING PLACES MANY WANT TO BE A MILLIONAIRE BUT ONLY A FEW ARE WILLING TO DO WHAT IT TAKES.",
  "#91 COLORS THERE’S ALWAYS SOMEONE OUT THERE LOOKING FORWARD TO PUTTING YOU OUT OF BUSINESS",
  "#92 BAD HABITS WILL EVENTUALLY CATCH UP TO YOU",
  "#93 GANGSTER SQUAD THERE’S ALWAYS SOMEONE OUT THERE WHO’S GUNNING FOR YOU",
  "#94 MIRACLE ALL THINGS SEEM IMPOSSIBLE AT FIRST",
  "#95 RUSH SOMETIMES YOUR FAMILY WON’T SUPPORT YOUR DREAMS",
  "#96 WHITE MEN CAN’T JUMP HIRE PEOPLE WHO ARE STRONG IN AREAS YOU’RE WEAK IN",
  "#97 FRIDAY NIGHT LIGHTS WHEN IT’S TIME TO COMPETE, YOU GOT TO BRING IT.",
  "#98 ARGO HOW TO NEGOTIATE WITH AN ENEMY",
  "#99 WHEN WE WERE KINGS SOMETIMES YOU NEED TO FOOL YOURSELF INTO GREATNESS",
  "#100 40 YEAR OLD VIRGIN MANY LOSE THEIR VIRGINITY IN BUSINESS LATE AND THAT’S OK.",
];
export { MoviesJson, MoviesCaption };
